# Generated by Django 2.2.13 on 2020-06-26 13:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(default=None, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='email address')),
                ('Business_Name', models.CharField(default=None, max_length=255, verbose_name='Bussiness Name')),
                ('Business_Website', models.CharField(blank=True, default=None, max_length=255, verbose_name='Bussiness Website')),
                ('First_Name', models.CharField(default=None, max_length=255, verbose_name='First Name')),
                ('Last_Name', models.CharField(blank=True, default=None, max_length=255, verbose_name='Last Name')),
                ('Phone_Number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, region=None, verbose_name='Phone Number')),
                ('gridCheck', models.BooleanField(default=False)),
                ('is_Influencer', models.BooleanField(default=False)),
                ('is_Brand', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
